### PR TITLE
Allow WebData to get a type

### PR DESCRIPTION
**Pull request by amitaibu**
#3

### CODE REVIEW

**Review by stoeffel — APPROVED** [review]
lgtm! 👍

**Comment by amitaibu** [comment]
Maybe in order to avoid breaking changes in existing code bases I can change `EditableWebData` to be an alias, and change the type name. Checking..

**Comment by amitaibu** [comment]
Yeah, the alias did the trick 😸 . @stoeffel looks ok to you?

**Comment by stoeffel** [comment]
> Maybe in order to avoid breaking changes in existing code bases I can change EditableWebData to be an alias, and change the type name. Checking..

I actually like it better without the type alias. I think major version changes aren't a bad thing if they are making things better. Additionally, it's easy to see where you need to fix your code. But it's up to you. I don't use this package as often as I used to (as well as RemoteData), because I found it simpler to use custom types for my specific use-cases.

**Comment by amitaibu** [comment]
> Additionally, it's easy to see where you need to fix your code

With that type alias, you actually don't need to fix existing code, so I think it's a nice plus.

> I don't use this package as often as I used to (as well as RemoteData), because I found it simpler to use custom types for my specific use-cases.

I actually use this, RemoteData and Editable quite a lot. I find they capture really well the notion of UI changes that need to be eventually sent to the backend.

**Pull request merged**
