### PR TITLE
Update RemoteData version

### PR DESCRIPTION
**Pull request by anvmn**
To eliminate possible dependency with `Skinney/murmur3`

### CODE REVIEW

**Comment by amitaibu** [comment]
See if we can maybe use this -- https://docs.travis-ci.com/user/languages/elm/

**Comment by anvmn** [comment]
@amitaibu 

All my attempts to make this work with `elm-0.19.1` have failed.
Ended up using `elm-0.19.0`, and Travis is green now.

**Comment by amitaibu** [comment]
Thanks, Travis is green, however it seems that tests are throwing an error

https://travis-ci.org/github/Gizra/elm-editable-webdata/builds/734066407#L325

image

**Comment by anvmn** [comment]
@amitaibu Better now:

Selection_999(1323)

**Comment by anvmn** [comment]
@amitaibu please review

**Review by amitaibu — COMMENTED** [review]
Looks good :+1: 

Please merge and publish to Elm as-well

**Pull request merged**
